- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import vpc variables
      include_vars: vars/vpc_setup
    
    - name: Create vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        tenancy: dedicated
      register: vpc_data
    
    - debug:
        var: vpc_data

    - name: Create a public subnet 1 
      ec2_vpc_subnet:
        vpc_id: "{{vpc_data.vpc.id}}"
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        map_public: yes
        resource_tags:
          Name: publicsubnet1
      register: pubsub1_data

    - name: Create a public subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{vpc_data.vpc.id}}"
        cidr: "{{PubSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        map_public: yes
        resource_tags:
          Name: publicsubnet2
      register: pubsub2_data

    - name: Create a public subnet 3
      ec2_vpc_subnet:
        vpc_id: "{{vpc_data.vpc.id}}"
        cidr: "{{PubSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        map_public: yes
        resource_tags:
          Name: publicsubnet3
      register: pubsub3_data

    - name: Create a private subnet 1 
      ec2_vpc_subnet:
        vpc_id: "{{vpc_data.vpc.id}}"
        cidr: "{{PriSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        resource_tags:
          Name: privatesubnet1
      register: prisub1_data

    - name: Create a private subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{vpc_data.vpc.id}}"
        cidr: "{{PriSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        resource_tags:
          Name: privatesubnet2
      register: prisub2_data

    - name: Create a private subnet 3
      ec2_vpc_subnet:
        vpc_id: "{{vpc_data.vpc.id}}"
        cidr: "{{PriSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        resource_tags:
          Name: privatesubnet3
      register: prisub3_data